config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  get 'note_shares/:id/update_edit_request', to: 'note_shares#update_edit_request', as: :update_edit_request

  resources :notes do
    member do
      get 'shownote'
      get 'sharednote'
      get 'important'
    end

    collection do
      get 'tags/:tag', to: 'notes#tagged_notes', as: :tag
      get 'note_shares/request_edit', to: 'note_shares#request_edit', as: :request_edit
      get 'note_shares/index'
      get 'note_shares/shared_by_me'
      get 'note_shares/request_view', to: 'note_shares#request_view', as: :request_view

      patch 'auto_save'
      patch 'notes_shares/edit_permission'
      patch 'notes_shares/view_permission'
    end

    resources :note_shares, only: %i[new create edit update destroy]
    resources :comments
  end

  resources :charges, only: %i[new create] do
    get 'refund', as: :refund, on: :collection
  end
  
  resources :refunds, only: %i[new create edit update]

  root 'notes#index'
end

app/models/note_share.rb
# frozen_string_literal: true

# Managing NoteShare
class NoteShare < ApplicationRecord
  # Associations
  belongs_to :note
  belongs_to :user

  # Validations
  validates :email, presence: true

  # Methods

  # Fetch the notes title
  def title
    note.title
  end

  # Fetch the notes description
  def description
    note.description
  end

  # Fetch the user username
  def username
    user.username
  end

end

app/controllers/note_shares_controller.rb
# frozen_string_literal: true

# Managing the notes sharing
class NoteSharesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: %i[
    show
    edit
    update
    destroy
    request_edit
    update_edit_request
  ]

  # GET /notes/note_shares/shared_by_me
  def shared_by_me
    @noteshares = NoteShare.includes(
      :note
    ).all.where(
      notes: { status: true },
      user_id: current_user.id
    ).distinct
  end

  # PATCH /notes/notes_shares/edit_permission
  def edit_permission
    if NoteShare.edit == true
      NoteShare.update(edit: false)
      respond_to do |format|
        format.js { render js: 'window.location.href = "notes";' }
      end
    else
      NoteShare.update(edit: true)
      respond_to do |format|
        format.js { render js: 'window.location.href = "notes";' }
      end
    end
  end

  # GET /notes/note_shares/request_edit
  def request_edit
    @sender_email = current_user.email
    @receiver_email = User.find(@note.user_id).email

    SendMailMailer.with(
      note: @note,
      sender_email: @sender_email,
      receiver_email: @receiver_email,
      noteurl: @note.id
    ).request_edit_email.deliver!
    redirect_to notes_path, notice: 'Edit Request Sent'
  end

  def update_edit_request
    if @noteshare.edit == true
      @noteshare.update(edit: false)
      redirect_to notes_path, notice: 'EDIT Access updated to false'
    elsif @noteshare.edit == false
      @noteshare.update(edit: true)
      redirect_to notes_path, notice: 'EDIT Access updated to true'
      @receiver_email = @noteshare.email
      @sender_email = current_user.email

      SendMailMailer.with(
        note: @note,
        sender_email: @sender_email,
        receiver_email: @receiver_email,
        noteurl: @note.id
      ).update_edit_request.deliver!
    end
  end

  def index
    @noteshares = NoteShare.includes(:note, :user).all.where(
      email: current_user.email
    ).where(
      notes: { status: true }
    ).distinct
  end

  def new
    @noteshare = NoteShare.new
    @notes = Note.all
    @note = @notes.find(params[:note_id])
  end

  def create
    email = User.where(
      email: params[:note_share][:email]
    ).exists?
    @name = current_user.username
    @note = Note.find(params[:note_id])
    @noteshare = @note.note_shares.create!(note_share_params)
    if @noteshare
      if email
        SendMailMailer.with(
          user: @noteshare,
          username: @name,
          noteurl: @noteshare.note_id
        ).note_email.deliver!
      else
        SendMailMailer.with(
          user: @noteshare,
          username: @name
        ).signup_email.deliver!
      end
    end
    respond_to do |format|
      format.js { render js: 'window.location.href = "notes";' }
    end
  end

  private

  def note_share_params
    params.require(:note_share).permit(
      :email,
      :user_id,
      :note_id,
      :edit,
      :view
    )
  end

  def set_note
    @noteshare = NoteShare.find(params[:id])
    @note = Note.find(params[:id])
  end
end

app/helpers/note_shares_helper.rb
# frozen_string_literal: true

# NoteSharesHelper
module NoteSharesHelper
end

app/views/note_shares/_index.html.erb
<div class="modal-dialog ">
  <div class="modal-content">
    <div class="modal-body">
      <% if noteshares.empty? %>
        <h4 class="message" align="center" >No Shared Notes</h4>
      <% else %>
        <h2 align="center">
          Shared notes
        </h2>
        <table class="table" border="2" >
          <thead class="table-dark">
            <tr>
              <th><center>No.</center></th>
              <th><center>Title</center></th>
              <th><center>Description</center></th>
              <th><center>View</center></th>
              <th><center>Edit</center></th>
              <th><center>Shared by</center></th>
              <th><center>Shared On</center></th>
            </tr>
          </thead>
          <tbody class="notes-index">
            <% no = 1 %>
            <% noteshares.each do |noteshare| %>
              <tr class="table-info">
                <td>
                  <%= no %>
                </td>
                <td class="text-dark">
                  <%= noteshare.title %>
                </td>
                <td>
                  <%= noteshare.description.html_safe %>
                </td>
                <td>
                  <% if noteshare.view == true %>
                    <%= link_to 'Show', shownote_note_path(noteshare) ,remote: true , class: "btn btn-info text-dark" %>
                  <% else %>
                    <%= link_to 'Request Access',request_view_path,class: "btn btn-info pull-right" ,remote: true %>
                  <% end %>
                </td>
                <td>
                  <% if noteshare.edit == true %>
                    <%= link_to 'Edit note', edit_note_path(noteshare), class: "btn btn-info pull-right" ,remote: true %>
                  <% else %>
                    <%= link_to 'Request Access',request_edit_notes_path(noteshare),class: "btn btn-info pull-right" %>
                  <% end %>
                </td>
                <td>
                  <%= noteshare.username %>
                </td>
                <td>
                  <%= noteshare.created_at %>
                </td>
              </tr>
              <% no += 1%>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/note_shares/_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_with model: [ note, note.note_shares.build ],remote: true do |f| %>
    <div class="modal-body">

      <div class="modal-header">
        <h3>Share with</h3>
      </div>

      <ul class="errors"></ul>

      <div class="form-group">
        <%= f.label 'Email' , class: "form-label" %>
        <%= f.email_field :email , class: "form-control" %>
      </div>

      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.hidden_field :note_id, value:  note.id %>

      <div class="form-group">
        <p><strong>Note:- </strong><b><u><%= note.title%></u></b></p>
        <p><strong>Permissions:- </strong>
          <b><%= f.check_box :edit %>Edit</b>
          <b><%= f.check_box :view %>View</b>
        </p>
      </div>

      <div class="modal-footer">
        <%= f.submit 'Share', class: "btn btn-primary" %>
        <%= link_to "Cancel", "#", class: "btn btn-danger", data: {dismiss: "modal"} %>
      </div>

    </div>
    <% end %>
  </div>
</div>

app/views/note_shares/_save.js.erb
$("ul.errors").html("")
<% if noteshare.errors.any? %>
  <% noteshare.errors.full_messages.each do |message| %>
  $("ul.errors").append($("<li style='color:red;'/>").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $("#note-form").modal("hide")
<% end %>

app/views/note_shares/_shared_by_me.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-body">
      <% if noteshares.empty? %>
        <h5 class="message">No Notes Shared by you</h5>
      <% else %>
      <h2 align="center">Shared by me</h2>

        <table class="table" border="2" >
          <thead class="table-dark">
            <tr>
              <th><center>No.</center></th>
              <th><center>Title</center></th>
              <th><center>Description</center></th>
              <th><center>View</center></th>
              <th><center>Edit</center></th>
              <th><center>Shared with<center></th>
              <th><center>Shared on<center></th>
            </tr>
          </thead>
          <tbody class="notes-index">
            <% no = 1 %>
            <% noteshares.each do |note| %>
              <tr class="table-info">
                <td>
                  <%= no %>
                </td>
                <td class="text-dark">
                  <%= note.note.title %>
                </td>
                <td>
                  <%= note.note.description.html_safe %>
                </td>
                <td>
                  <% if note.view == true %>
                    <span class="glyphicon glyphicon-ok-sign bg-success"></span>
                  <% else %>
                    <span class="glyphicon glyphicon-remove-sign bg-danger"></span>
                  <% end %>
                </td>
                <td>
                  <%= link_to "#{ note.edit ? 'ALLOW' : 'DENY' }",
                    update_edit_request_path(note),
                   method: :get,
                   class: "btn btn-xs btn-#{ note.edit ? 'success' : 'danger' }"
                  %>
                </td>
                <td>
                  <%= note.email%>
                </td>
                <td>
                  <%= note.created_at %>
                </td>
              </tr>
            <% no += 1%>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/note_shares/create.js.erb
<%= render 'save', noteshare: @noteshare %>

app/views/note_shares/edit_permission.js.erb
<% if NoteShare.edit == true %>
  $(".autosave").html('True').removeClass('btn-warning').addClass('btn-success')
<% else %>
  $(".autosave").html('False').removeClass('btn-success').addClass('btn-warning')
<% end %>

app/views/note_shares/index.js.erb
$("#index-form").html(" <%= escape_javascript(render 'index', noteshares: @noteshares) %>" );

app/views/note_shares/new.js.erb
$("#note-form").html(" <%= escape_javascript(render 'new', note: @note) %>" );
$("#note-form").modal("show");

app/views/note_shares/shared_by_me.js.erb
$("#index-form").html(" <%= escape_javascript(render 'shared_by_me', noteshares: @noteshares) %>" );