config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  get 'note_shares/:id/update_edit_request', to: 'note_shares#update_edit_request', as: :update_edit_request

  resources :notes do
    member do
      get 'shownote'
      get 'sharednote'
      get 'important'
    end

    collection do
      get 'tags/:tag', to: 'notes#tagged_notes', as: :tag
      get 'note_shares/request_edit', to: 'note_shares#request_edit', as: :request_edit
      get 'note_shares/index'
      get 'note_shares/shared_by_me'
      get 'note_shares/request_view', to: 'note_shares#request_view', as: :request_view

      patch 'auto_save'
      patch 'notes_shares/edit_permission'
      patch 'notes_shares/view_permission'
    end

    resources :note_shares, only: %i[new create edit update destroy]
    resources :comments
  end

  resources :charges, only: %i[new create] do
    get 'refund', as: :refund, on: :collection
  end
  
  resources :refunds, only: %i[new create edit update]

  root 'notes#index'
end

app/models/note.rb
# frozen_string_literal: true

# Managing Note Model
class Note < ApplicationRecord
  # Associations
  belongs_to :user
  has_many(
    :comments,
    dependent: :destroy
  )
  has_many :note_shares
  #has_many :tags, through: :taggings

  # Validations
  validates :user, presence: true
  validates :title, presence: true
  validates(
    :description,
    presence: true,
    length: {
      minimum: 5,
      maximum: 500
    }
  )

  acts_as_taggable_on :tags
end

app/controllers/notes_controller.rb
# frozen_string_literal: true

# Managing the notes
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: %i[
    show
    edit
    update
    destroy
    shownote
    sharednote
    important
    unimportant
  ]

  # GET /notes/1/important
  def important
    if @note.important == true
      # render plain:[@note].inspect
      @note.update(important: false)
      redirect_to notes_path
    elsif @note.important == false
      @note.update(important: true)
      redirect_to notes_path
    end
  end

  # PATCH /notes/auto_save
  def auto_save
    if current_user.autosave == true
      current_user.update(autosave: false)
      respond_to do  |format|
        format.js { render js: 'window.location.href = "notes";' }

      end
    else
      current_user.update(autosave: true)
      respond_to do  |format|
        format.js {render js: 'window.location.href = "notes";' }
      end
    end
  end

  # GET /notes/tags/:tag
  def tagged_notes
    if params[:tag]
      @notes = Note.tagged_with(params[:tag]).where(
        user_id: current_user.id,
        status: true
      )
    end
  end

  # GET /notes
  # GET /notes.json
  def index
    @note = Note.where(user_id: current_user.id, status: true)
    @notes =
      if params[:search]
        @notes = Note.includes(:tags,:taggings).references(:tags).where(
          'notes.title LIKE :search OR notes.description LIKE :search OR tags.name LIKE :search',
          search: "%#{params[:search]}%"
        ).paginate(
          page: params[:page],
          per_page: 4
        ).where(
          status: true,
          user_id: current_user.id
        ).distinct
      else
        @notes = Note.includes(:tags,:taggings).references(:tags).where(
          status: true,
          user_id: current_user.id
        ).order(
          created_at: :desc
        ).paginate(
          page: params[:page],
          per_page: 4
        )
      end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show; end

  # GET /notes/1/shownote
  def shownote
    @comments = Note.paginate(page: params[:page], per_page: 2)
    @edit = @note.note_shares.find_by(edit: true)
    @user = @note.user.id
    # render plain:[@edit,@user].inspect
  end

  # GET /notes/1/sharednote
  def sharednote
    @comments = Note.paginate(page: params[:page], per_page: 2)
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
    respond_to do |format|
      format.html # edit.html.erb
      format.js # edit.js.erb
      format.json { render json: @note }
    end
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.save
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    @note.update(note_params)

    respond_to do |format|
      format.json { render json: flash.to_hash }
    end

  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.update(status: false)
    respond_to do |format|
      format.html do
        redirect_to notes_url,
        notice: 'Note was successfully destroyed.'
      end
      format.json do
        head :no_content
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_note
    @note = Note.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def note_params
    params.require(:note).permit(
      :title,
      :description,
      :user_id,
      :tag_list,
      :important
    )
  end
end

app/helpers/notes_helper.rb
# frozen_string_literal: true

# NotesHelper
module NotesHelper
end

app/views/notes/_edit.html.erb
<%# render 'form', note: @note %>
<%# link_to 'Show', @note %> |
<%# link_to 'Back', notes_path %>
<%= tinymce_assets %>
<div class="modal-dialog">

  <div class="modal-content">
    <%= form_for note,remote: true, :html=> {:id => 'note'}  do |form| %>
      <div class="modal-body">

        <div class="modal-header">
          <h1>Note</h1>
        </div>

        <ul class="errors"></ul>

        <div class="form-group">
          <%= form.label :title, class: "control-label" %>
          <%= form.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :description, class: "control-label"  %>
          <%= form.text_area :description, class: "tinymce"  %>
        </div>

        <div class="form-group">
          <%= form.label :tag_list, 'Tags (separated by commas)', class: "control-label"  %>
          <%= form.text_field :tag_list ,class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.hidden_field :user_id, :value => current_user.id %>
        </div>

        <div class="form-group">
          <%= form.check_box :important %>Mark as Imp
        </div>

        <div class="modal-footer">
          <div class="actions">
            <% if current_user.autosave == false %>
              <%= form.submit class: "btn btn-success" %>
            <% end %>
            <% if current_user.autosave == true %>
              <script type="text/javascript">
                function autosaveForm() {
                  alert('hello');
                  tinymce.triggerSave();
                  $.ajax({
                   type: "PATCH",
                   url: "<%= note_path(note) %>",
                   data: $("#note").serialize(),
                   dataType: 'json',
                   success: function(data) {
                     console.log(data);
                     console.log("Update DONE")
                   }
                 }).done(function (data){
                   alert(data.notice +  " Update DONE");
                   window.location.href = "notes";
                 }).fail(function (data){
                   alert(data.alert +  " update ERROR")
                 });
                }//end of function
                setInterval(autosaveForm, 5000); //Every 5 seconds autosaveform function will call
              </script>
            <% end %>
            <%= link_to "Cancel", "#", class: "btn btn-danger", data: {dismiss: "modal"} %>
          </div>
        </div>

      </div>
    <% end %>
  </div>

<%= tinymce %>
</div>

app/views/notes/_index.html.erb
<div class="col-md-8">
  <% if note.empty? %>
    <h4 class="message" align="center" > No Notes <br><br>
      <%= link_to 'Create', new_note_path , class: "btn btn-primary", remote: true %>
    </h4>

  <% else %>
    <table class="table" border="2" >
      <thead class="table-dark">
        <tr>
          <th><center>No.</center></th>
          <th><center>Title</center></th>
          <th><center>Description</center></th>
          <th colspan="3"><center>Actions</center></th>
        </tr>
      </thead>
      <tbody class="notes-index">
        <% no = 1%>
        <% note.each do |note| %>
          <tr class="table-info">
            <td>
              <%= no %>
            </td>
            <td class="text-dark">
              <%= note.title %>
            </td>
            <td>
              <%= note.description.html_safe %>
            </td>
            <td>
              <%= link_to 'Show',
               note,
               remote: true,
               class: "btn btn-info text-dark"
              %>
            </td>
            <td>
              <%= link_to 'Edit',
               edit_note_path(note),
               remote: true,
               class: "btn btn-primary text-dark"
              %>
            </td>
            <td>
              <%= link_to 'Delete',
                note,
                method: :delete,
                data: { confirm: 'Are you sure?' },
                class: "btn btn-danger text-dark"
              %>
            </td>
          </tr>
          <% no += 1%>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/notes/_save.js.erb
$("ul.errors").html("")
<% if note.errors.any? %>
  <% note.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li style='color:red;'/>").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $("#note-form").modal("hide")
  $(window.location.replace("/notes"))
<% end %>

app/views/notes/_show.html.erb
<div class="container-fluid col col-md-4">
  <table border="1" class="table" width="500px">
    <tr>
      <td><strong><h2><%= note.title %></h2></strong></td>
    </tr>
    <tr>
      <td><%= note.description.html_safe %></td>
    </tr>
  </table>

  <%= link_to 'Edit note', edit_note_path(note), class: "btn btn-info" ,remote: true%>
</div>

<div class="container-fluid col col-md-4">
  <h2>Comment</h2>
  <%= render note.comments, note: note%>
  <div id="comment-form"></div>
  <p><%= render 'comments/new'%></p>
  <%= link_to "Cancel", "#", class: "btn btn-danger", data: {dismiss: "modal"} %>
</div>

app/views/notes/auto_save.js.erb
<% if current_user.autosave == true %>
  $(".autosave").html('True').removeClass('btn-warning').addClass('btn-success')
<% else %>
  $(".autosave").html('False').removeClass('btn-success').addClass('btn-warning')
<% end %>

app/views/notes/create.js.erb
<%= render "save" , note: @note %>

app/views/notes/dashboard.html.erb
<%= render 'layouts/header'%>

app/views/notes/edit.js.erb
$("#note-form").html(" <%= escape_javascript(render 'edit', note: @note) %>" );
$("#note-form").modal("show");

app/views/notes/index.html.erb
<%= render 'layouts/header', note: @note, noteshare: @noteshare %>
<p id="notice" align="center" ><%= notice %></p>

<div class="container-fluid pull-left col-md-2.5 bg-info" >
  <div align="center">
    <%= link_to "New Note",
     new_note_path,
     remote: true ,
     class: "btn btn-info new-note  size "
    %>
  </div>
  <%= render 'layouts/side-menu', notes: @notes %>

</div>

<br>

<%= link_to 'Pay', new_charge_path, class: "btn btn-info", remote: true%>
<%= link_to 'Request Refund', new_refund_path, class: "btn btn-primary", remote: true %>
<%# render 'layouts/welcome_page'%>

<%# link_to 'New Note', new_note_path, remote: true %>
<div class="modal fade" id="note-form"></div>

<div id="index-form" class="index-form">
  <%= render 'layouts/welcome_page'%>
</div>
  <%# render 'layouts/footer'%>

app/views/notes/new.js.erb
$("#note-form").html(" <%= escape_javascript(render 'new', note: @note) %>" )
$("#note-form").modal("show")

app/views/notes/show.js.erb
$("#index-form").html(" <%= escape_javascript(render 'show', note: @note) %>" );

app/views/notes/shownote.js.erb
$("#index-form").html(" <%= escape_javascript(render 'shownote',note: @note, comments: @comments, edit: @edit, user: @user ) %>")

app/views/notes/tagged_notes.js.erb
$("#note-form").html(" <%= escape_javascript(render 'tagged_notes', notes: @notes) %>" );
$("#note-form").modal("show");

app/views/notes/update.js.erb
<%= render "save", note: @note %>