config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  get 'note_shares/:id/update_edit_request', to: 'note_shares#update_edit_request', as: :update_edit_request

  resources :notes do
    member do
      get 'shownote'
      get 'sharednote'
      get 'important'
    end

    collection do
      get 'tags/:tag', to: 'notes#tagged_notes', as: :tag
      get 'note_shares/request_edit', to: 'note_shares#request_edit', as: :request_edit
      get 'note_shares/index'
      get 'note_shares/shared_by_me'
      get 'note_shares/request_view', to: 'note_shares#request_view', as: :request_view

      patch 'auto_save'
      patch 'notes_shares/edit_permission'
      patch 'notes_shares/view_permission'
    end

    resources :note_shares, only: %i[new create edit update destroy]
    resources :comments
  end

  resources :charges, only: %i[new create] do
    get 'refund', as: :refund, on: :collection
  end
  
  resources :refunds, only: %i[new create edit update]

  root 'notes#index'
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new

  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })

    if charge.paid
      # flash[:notice] = "Payment successful"
      current_user.update(stripe_charge_id: charge.id)
      redirect_to notes_path, notice: "Payment successful"
    #else
      #  flash[:warning] = "Payment proccess failed. Try Again.!"
    end


    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end

#   def refund
#     id = User.find(params[:id])
#     render plain:[id].inspect
#     #refunded = Stripe::Refund.create({ charge: refund.user_chargeid,})
#     # charge = Stripe::Charge.retrieve(charge: refund.user_chargeid)
#     # refunded = charge.refund
#     # refunded = Stripe::Refund.create({ charge: refund.strip_charge_id,})
#     refund = Stripe::Refund.create({
#     charge: find(:stripe_charge_id),
# })
#
#     if refunded.status == succeeded
#       current_user.update(refunded: true)
#       redirect_to notes_path, notice: "Refund successful"
#     end
#   end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/1create.js.erb
$("#index-form").html(" <%= escape_javascript(render 'charges/create') %>" )
$("#index-form").modal("show")

app/views/charges/_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_tag charges_path do %>
      <div class="modal-body">
          <article>
            <% if flash[:error].present? %>
              <div id="error_explanation">
                <p><%= flash[:error] %></p>
              </div>
            <% end %>
            <label class="amount">
              <span>Amount: $5.00</span>
            </label>
          </article>
          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-description="A month's subscription"
                  data-amount="500"
                  data-locale="auto"
          ></script>
      </div>
    <% end %>
  </div>
</div>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong> $5.00</strong>!</h2>

app/views/charges/new.js.erb
$("#index-form").html(" <%= escape_javascript(render 'charges/new') %>" )
$("#index-form").modal("show")