config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  get 'note_shares/:id/update_edit_request', to: 'note_shares#update_edit_request', as: :update_edit_request

  resources :notes do
    member do
      get 'shownote'
      get 'sharednote'
      get 'important'
    end

    collection do
      get 'tags/:tag', to: 'notes#tagged_notes', as: :tag
      get 'note_shares/request_edit', to: 'note_shares#request_edit', as: :request_edit
      get 'note_shares/index'
      get 'note_shares/shared_by_me'
      get 'note_shares/request_view', to: 'note_shares#request_view', as: :request_view

      patch 'auto_save'
      patch 'notes_shares/edit_permission'
      patch 'notes_shares/view_permission'
    end

    resources :note_shares, only: %i[new create edit update destroy]
    resources :comments
  end

  resources :charges, only: %i[new create] do
    get 'refund', as: :refund, on: :collection
  end
  
  resources :refunds, only: %i[new create edit update]

  root 'notes#index'
end

app/views/layouts/_footer.html.erb
<div class="footer" style="margin-top:20px;">
  <div class="pull-right" style="font-size:18px; color:red;">
    <%= Date.today%>&nbsp&nbsp<%= Time.now.strftime("%I:%M:%S")%>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse sticky-top">
  <div class="container-fluid" >
    <div class="navbar-header" >
      <%= link_to '|\|ØTÊ$', notes_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">

      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Home', notes_path %>
        </li>
        <li>
          <%= link_to 'My notes', notes_path ,remote: true%>
        </li>
        <li>
          <%= link_to 'Shared notes',
            note_shares_index_notes_path(note,noteshare),
            remote: true
          %>
        </li>
        <li>
          <%= link_to 'Shared by me',
            note_shares_shared_by_me_notes_path(note,noteshare),
            remote: true
          %>
        </li>
      </ul>

      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>

          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.username %>
              <span class="caret"></span>
            </a>

            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to 'Profile', edit_user_registration_path %>
              </li>
              <li>
                <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>

        <% else %>
          <li>
            <%= link_to 'Log In', new_user_session_path %>
          </li>
          <li>
            <%= link_to 'Sign Up', new_user_registration_path %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/_side-menu.html.erb
<br>
<div class="d-block bg-danger col-md-6 pull-right">
  <h5>Autosave&nbsp&nbsp
    <span>
      <%= link_to "#{ current_user.autosave ? 'ON' : 'OFF' }",
        auto_save_notes_path,
        method: :patch,
        remote: true,
        class: "btn btn-xs btn-#{ current_user.autosave ? 'success' : 'danger' }"
      %>
    </span>
  </h5>
</div>

<br><br><br>

<%= form_with  method: :get, url: notes_path ,local: true  do |f| %>
  <%= f.search_field :search , class: "size" %>
  <%= f.submit 'Search', class: "btn btn-success pull-right" %>
<% end %>

<div class="sidemenu">
  <table class="table table-hover bg-info" style="text-decoration:none;">
    <tbody>
      <% notes.each do |note| %>
        <tr ">
          <td>
            <%= link_to note.title,
             shownote_note_path(note),
             class: "title",
             # style: "text-decoration:none;color:#000066;",
             remote: true
            %>
            <span>&nbsp</span>
            <%=link_to "",
              new_note_note_share_path(note),
              class: "glyphicon glyphicon-share share",
              remote: true
              # style: "font-size:15px;text-decoration:none;",
            %>

            <% if note.important == true %>
              <%=link_to "",
                important_note_path(note),
                class: "glyphicon glyphicon-check pull-right important"
                # style: "font-size:15px;text-decoration:none;color:#3333ff"
              %>
            <% else %>
              <%=link_to "",
                important_note_path(note),
                class: "glyphicon glyphicon-unchecked pull-right important"
                # style: "font-size:15px;text-decoration:none;color:#3333ff"
              %>
            <% end %>

            <br>

            <%= link_to "",
              note,
              method: :delete,
              data: { confirm: 'Are you sure?'},
              class: "glyphicon glyphicon-trash data-toggle='tooltip' title='Delete' delete "
              # style: "color:#ff0000;font-size:15px;"
            %>
            <%= link_to "",
              edit_note_path(note),
              class: "glyphicon glyphicon-edit edit",
              # style: "color:black;font-size:15px;",
              remote: true
            %>

            <div class="pull-right">
              <%= raw(
                note.tag_list.map { |t| link_to t, tag_notes_path(t) ,
                 remote: true
                }.join(' '))
              %>
            </div>

          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate notes %>
</div>

app/views/layouts/_welcome_page.html.erb
<h3 align="center">
  <%= greet %> <u class="greetings"><%= current_user.username %></u>

  <br><br>

  <%=link_to new_note_path, remote: true do %>
    <%= image_tag ("note.png")%>
  <% end %>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotesApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if user_signed_in? %>

    <% else %>
      <p class="notice" align="center"><%= notice %></p>
      <p class="alert" align="center" ><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>